# Generated by Django 3.0.3 on 2020-10-22 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('lastPrice', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerRange', models.IntegerField(null=True)),
                ('upperRange', models.IntegerField(null=True)),
                ('lowerStDev', models.IntegerField(null=True)),
                ('upperStDev', models.IntegerField(null=True)),
                ('technicalLow', models.IntegerField(null=True)),
                ('technicalHigh', models.IntegerField(null=True)),
                ('week3DonchianLow', models.IntegerField(null=True)),
                ('week3DonchianHigh', models.IntegerField(null=True)),
                ('stDev', models.IntegerField(null=True)),
                ('stDevPercent', models.CharField(max_length=200, null=True)),
                ('volumeChange', models.CharField(max_length=200, null=True)),
                ('percentUpside', models.CharField(max_length=200, null=True)),
                ('percentDownside', models.CharField(max_length=200, null=True)),
                ('month3Trend', models.CharField(max_length=200, null=True)),
                ('signal', models.CharField(max_length=200, null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week52', models.IntegerField(null=True)),
                ('day5ChangePercent', models.IntegerField(null=True)),
                ('month1ChangePercent', models.IntegerField(null=True)),
                ('day50MovingAvg', models.IntegerField(null=True)),
                ('day200MovingAvg', models.IntegerField(null=True)),
                ('fromHigh', models.IntegerField(null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastEPS', models.IntegerField(null=True)),
                ('consensusEPS', models.IntegerField(null=True)),
                ('trailingEPS', models.IntegerField(null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
    ]
