# Generated by Django 3.0.3 on 2020-10-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='index_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Index'),
        ),
    ]
