# Generated by Django 3.0.3 on 2020-10-22 23:39

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201022_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='consensusEPS',
        ),
        migrations.RemoveField(
            model_name='earnings',
            name='lastEPS',
        ),
        migrations.AddField(
            model_name='earnings',
            name='previousConsensus',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='earnings',
            name='previousEps',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='earnings',
            name='ttmEPS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('lastPrice', models.IntegerField(null=True)),
                ('stock_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peRatio', jsonfield.fields.JSONField(null=True)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Watchlist')),
            ],
        ),
        migrations.AlterField(
            model_name='earnings',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Watchlist'),
        ),
    ]
