# Generated by Django 3.0.3 on 2020-10-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20201022_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='index_id',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='trend',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='valuation',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='vol',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
