# Generated by Django 3.0.3 on 2020-10-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201022_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='lastPrice',
        ),
    ]
