# Generated by Django 3.0.3 on 2020-10-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201023_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock'),
        ),
        migrations.AlterField(
            model_name='valuation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock'),
        ),
    ]
