# Generated by Django 3.0.3 on 2020-10-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201023_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='ttmEPS',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lastPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='day200MovingAvg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='day50MovingAvg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='day5ChangePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='fromHigh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='month1ChangePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='week52',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='lowerRange',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='lowerStDev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='stDev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='technicalHigh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='technicalLow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='upperRange',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='upperStDev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='week3DonchianHigh',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vol',
            name='week3DonchianLow',
            field=models.FloatField(null=True),
        ),
    ]
