# Generated by Django 3.0.3 on 2020-10-23 05:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201023_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='ytdChangePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='day200MovingAvg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='day50MovingAvg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='day5ChangePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='fromHigh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='month1ChangePercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='peRatio',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='previousConsensus',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='previousEps',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='ttmEPS',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='week52',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='ytdChangePercent',
            field=models.FloatField(null=True),
        ),
    ]
