# Generated by Django 3.0.3 on 2020-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20201023_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='lastPrice',
            field=models.FloatField(null=True),
        ),
    ]
