# Generated by Django 3.0.3 on 2020-10-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_watchlist_lastprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='previousConsensus',
            new_name='reportedConsensus',
        ),
        migrations.RenameField(
            model_name='earnings',
            old_name='previousEps',
            new_name='reportedEPS',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='previousConsensus',
            new_name='reportedConsensus',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='previousEps',
            new_name='reportedEPS',
        ),
    ]
