# Generated by Django 3.0.3 on 2020-10-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='index',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
