# Generated by Django 3.0.3 on 2020-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20201027_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='index',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
