# Generated by Django 3.0.3 on 2020-10-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_stock_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
