# Generated by Django 3.0.3 on 2020-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20201027_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='avgPricetarget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='highPriceTarget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='lowPriceTarget',
            field=models.FloatField(null=True),
        ),
    ]
