# Generated by Django 3.0.3 on 2020-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20201109_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avgPricetarget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='highPriceTarget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='lowPriceTarget',
            field=models.FloatField(null=True),
        ),
    ]
