# Generated by Django 3.0.3 on 2020-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20201109_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='lowPriceTarget',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='lowPriceTarget',
        ),
    ]
