# Generated by Django 3.0.3 on 2020-11-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20201109_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avgPricetarget',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='fromPriceTarget',
            field=models.FloatField(null=True),
        ),
    ]
