# Generated by Django 3.0.3 on 2020-11-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20201109_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='fromPriceTarget',
            field=models.FloatField(null=True),
        ),
    ]
