# Generated by Django 3.0.3 on 2020-11-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_trend_frompricetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('lastPrice', models.FloatField(null=True)),
                ('week52', models.FloatField(null=True)),
                ('avg30Volume', models.FloatField(null=True)),
                ('day5ChangePercent', models.FloatField(null=True)),
                ('month1ChangePercent', models.FloatField(null=True)),
                ('month3ChangePercent', models.FloatField(null=True)),
                ('ytdChangePercent', models.FloatField(null=True)),
                ('day50MovingAvg', models.FloatField(null=True)),
                ('day200MovingAvg', models.FloatField(null=True)),
                ('fromHigh', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
    ]
