# Generated by Django 3.0.3 on 2020-11-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_macrotrend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macrotrend',
            options={'verbose_name': 'MacroTrend', 'verbose_name_plural': 'MacroTrends'},
        ),
    ]
