# Generated by Django 3.0.3 on 2020-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20201112_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrotrend',
            name='avg30Volume',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
