# Generated by Django 3.0.3 on 2020-11-29 06:37

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20201112_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', jsonfield.fields.JSONField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.CharField(max_length=200, null=True)),
                ('netIncome', models.FloatField(null=True)),
                ('netWorth', models.FloatField(null=True)),
                ('shortTermDebt', models.FloatField(null=True)),
                ('longTermDebt', models.FloatField(null=True)),
                ('debtToEquity', models.FloatField(null=True)),
                ('priceToSales', models.FloatField(null=True)),
                ('EBITDA', models.FloatField(null=True)),
                ('freeCashFlow', models.FloatField(null=True)),
                ('freeCashFlowPerShare', models.FloatField(null=True)),
                ('freeCashFlowYield', models.FloatField(null=True)),
                ('longTermDebtToEquity', models.FloatField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stock')),
            ],
            options={
                'verbose_name_plural': 'financials',
            },
        ),
    ]
