# Generated by Django 3.0.3 on 2020-11-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_financials_historicalprices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprices',
            options={'verbose_name_plural': 'historicalprices'},
        ),
    ]
