# Generated by Django 3.0.3 on 2020-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20201129_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='totalCash',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='totalDebt',
            field=models.FloatField(null=True),
        ),
    ]
