# Generated by Django 3.0.3 on 2020-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20201129_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
