# Generated by Django 3.0.3 on 2020-11-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrotrend',
            name='ticker',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
