# Generated by Django 3.0.3 on 2020-12-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20201130_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprices',
            name='datapoints',
            field=models.IntegerField(null=True),
        ),
    ]
