# Generated by Django 3.1.5 on 2021-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_auto_20210127_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlation',
            name='datapoints',
            field=models.IntegerField(null=True),
        ),
    ]
